sudo: false
language: generic
cache:
  timeout: 360
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
jobs:
  include:
    # - stage: build cabal
    #   script: stack --docker --no-terminal --install-ghc build -j 1 Cabal
    - stage: build dependencies for test
      script: stack --docker --no-terminal test --only-dependencies
    - stage: run test
      script: stack --docker --no-terminal test --no-run-benchmarks --no-haddock-deps --pedantic
    - stage: push docker image
      if: branch = master AND type = push
      script:
      - stack --docker --local-bin-path=./bin install
      - docker build -t $TRAVIS_REPO_SLUG . --build-arg local_bin_path=./bin
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $TRAVIS_REPO_SLUG
    - stage: push docker image
      if: tag IS present
      script:
      - stack --docker --local-bin-path=./bin install
      - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_TAG . --build-arg local_bin_path=./bin
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG

deploy:
  - provider: script
    script: bash .travis/deploy.bash
    on:
      branch: master
