name:                whoami
version:             0.1.0.0
github:              "matsubara0507/whoami"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall

description:         Please see the README on Github at <https://github.com/matsubara0507/whoami#readme>

dependencies:
- base >= 4.7 && < 5
- extensible
- extensible-instances
- lens
- text
- yaml

library:
  source-dirs: src
  dependencies:
  - aeson-pretty
  - containers
  - data-default
  - exceptions
  - megaparsec
  - mtl
  - req
  - text-conversions
  - scalpel-core

executables:
  whoami-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whoami

tests:
  whoami-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whoami
    - tasty
    - tasty-hunit
