name:                whoami
version:             0.2.0.0
github:              "matsubara0507/whoami"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path

description:         Please see the README on Github at <https://github.com/matsubara0507/whoami#readme>

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- StandaloneDeriving
- TemplateHaskell
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- extensible
- rio
- mix
- yaml

library:
  source-dirs: src
  dependencies:
  - aeson-pretty
  - megaparsec
  - req >= 2.0.0
  - text-conversions
  - scalpel-core
  - feed

executables:
  whoami:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - whoami
    - gitrev

tests:
  whoami-test:
    main:                Driver.hs
    source-dirs:         test
    dependencies:
    - heredoc
    - whoami
    - tasty
    - tasty-hunit
