resolver: nightly-2022-05-05
packages:
- .
extra-deps:
# - extensible-0.8.3
- github: fumieval/extensible
  commit: 4a1edb50c90d377085fcc3bad4c9f6e9d296b00e
- incremental-0.3.1
- membership-0.0.1
- github: matsubara0507/mix.hs
  commit: 9bcd386526fe10a025a23e951c2de86b05129b17
  subdirs:
  - mix

docker:
  repo: ghcr.io/matsubara0507/stack-build:20.04
  enable: false
