resolver: lts-14.6
packages:
- .
extra-deps:
- extensible-0.6.1
- membership-0
- req-2.0.1
- retry-0.8.0.1
- github: matsubara0507/mix.hs
  commit: 4978a33dec736799b30c14e215f7fa0f29fa2884
  subdirs:
  - mix

docker:
  repo: matsubara0507/stack-build
  enable: false
