github: [metadata]
encoding: UTF-8
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
markdown: redcarpet 
redcarpet: 
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]
